name: torchstaar
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - torchtriton=3.1
  - numpy=1.26
  - scipy=1.13
  - pandas>=1.4
  - xarray>=2024.1
  - matplotlib>=3.7
  - zstandard>=0.22
  - pip
  - setuptools
  - wheel
  - git
  - cxx-compiler
  - zlib
  - xz
  - pytest
  - pip:
      - rdata==1.1.0
      - -e .
