source('validation/compare_logp.R')
source('validation/compare_nonp.R')
suppressPackageStartupMessages(library(Matrix))
a <- list(data.frame(pvalue=c(.1,.01),pvalue_log10=c(1,2),MAF=c(.1,.2),Score=c(3,4),Est_se=c(.2,.3)))
b <- a;b[[1]]$pvalue[] <- c(.8,.9);b[[1]]$pvalue_log10[] <- c(9,8)
attributes(b[[1]]) <- attributes(a[[1]])
x <- compare_nonp_objects(a,b)
stopifnot(x$passed,x$skipped_p_cells==4,x$numeric_cells==6,!compare_logp_objects(a,b)$logp_passed)
for(name in c('MAF','Score','Est_se')) {
 b <- a;b[[1]][[name]][1] <- b[[1]][[name]][1]+1
 attributes(b[[1]]) <- attributes(a[[1]])
 stopifnot(!compare_nonp_objects(a,b)$passed)
}
b <- a;names(b[[1]]) <- rev(names(b[[1]]));stopifnot(!compare_nonp_objects(a,b)$passed)
b <- a;b[[1]]$pvalue[1] <- NA_real_;stopifnot(!compare_nonp_objects(a,b)$passed)
a <- list(matrix(list(.1,5,'meta',.2),2,dimnames=list(NULL,c('STAAR-O','meta'))))
b <- a;b[[1]][[1]] <- .8;stopifnot(compare_nonp_objects(a,b)$passed)
b[[1]][[4]] <- .7;stopifnot(!compare_nonp_objects(a,b)$passed)
a <- matrix(c(.1,.2,4,5),2,dimnames=list(NULL,c('pvalue','Score')))
b <- a;b[,1] <- c(.8,.9);stopifnot(compare_nonp_objects(a,b)$passed)
b[1,2] <- 9;stopifnot(!compare_nonp_objects(a,b)$passed)
a <- list(N=2L,meta='x',null=Matrix(diag(c(1,2)),sparse=TRUE),special=c(NA_real_,NaN,Inf,-Inf))
stopifnot(compare_nonp_objects(a,a)$passed)
b <- a;b$null@x[1] <- b$null@x[1]+1;stopifnot(!compare_nonp_objects(a,b)$passed)
b <- a;b$special[2] <- NA_real_;stopifnot(!compare_nonp_objects(a,b)$passed)
b <- a;b$special[4] <- Inf;stopifnot(!compare_nonp_objects(a,b)$passed)
b <- a;b$N <- 3L;stopifnot(!compare_nonp_objects(a,b)$passed)
stopifnot(compare_nonp_objects(list(x=1),list(x=1+5e-8))$passed)
stopifnot(!compare_nonp_objects(list(x=1),list(x=1+5e-7))$passed)
cat('NONP_CONTROLS_PASS\n')
